services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: yukina-lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx2G\n      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins:/opt/Lavalink/plugins
    ports:
      - "2333:2333"
    networks:
      - lavalink

networks:
  lavalink:
    name: yukina-lavalink
